<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="EPINPUNW05A9" failures="1" tests="18" name="CalculatorTest" time="0.077" errors="0" timestamp="2024-06-24T14:39:52 IST">
  <testcase classname="TestNG_Project.CalculatorTest" name="testDivByZero" time="0.001"/>
  <testcase classname="TestNG_Project.CalculatorTest" name="testDivNegative" time="0.004"/>
  <testcase classname="TestNG_Project.CalculatorTest" name="testMultNegative" time="0.0"/>
  <testcase classname="TestNG_Project.CalculatorTest" name="testDivPositive" time="0.0"/>
  <testcase classname="TestNG_Project.CalculatorTest" name="testPowNegative" time="0.0"/>
  <testcase classname="TestNG_Project.CalculatorTest" name="testMultPositive" time="0.0"/>
  <testcase classname="TestNG_Project.CalculatorTest" name="testPowPositive" time="0.0"/>
  <testcase classname="TestNG_Project.CalculatorTest" name="testSubNegative" time="0.0"/>
  <testcase classname="TestNG_Project.CalculatorTest" name="testSumNegative" time="0.0"/>
  <testcase classname="TestNG_Project.CalculatorTest" name="testSubPositive" time="0.0"/>
  <testcase classname="TestNG_Project.CalculatorTest" name="testSumPositive" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [5] but found [6]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [6]
at TestNG_Project.CalculatorTest.testSumPositive(CalculatorTest.java:36)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- testSumPositive -->
  <testcase classname="TestNG_Project.CalculatorTest" name="testSumWithDataProvider" time="0.003"/>
  <testcase classname="TestNG_Project.CalculatorTest" name="testMultiplyAfterAddition" time="0.001"/>
  <testcase classname="TestNG_Project.CalculatorTest" name="testSumWithDataProvider" time="0.0"/>
  <testcase classname="TestNG_Project.CalculatorTest" name="testSumWithDataProvider" time="0.0"/>
  <testcase classname="TestNG_Project.CalculatorTest" name="testSumWithDataProvider" time="0.0"/>
  <testcase classname="TestNG_Project.CalculatorTest" name="testSubtractAfterAddition" time="0.0">
    <skipped/>
  </testcase> <!-- testSubtractAfterAddition -->
  <testcase classname="TestNG_Project.CalculatorTest" name="testPowerAfterAddition" time="0.0">
    <skipped/>
  </testcase> <!-- testPowerAfterAddition -->
  <testcase classname="TestNG_Project.CalculatorTest" name="testDivideAfterAddition" time="0.0">
    <ignored/>
  </testcase> <!-- testDivideAfterAddition -->
</testsuite> <!-- CalculatorTest -->
